-- Counters
CREATE SEQUENCE EntrantSeq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SpecTestSeq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE HeiSpecSeq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE EntTestSeq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SpecSeq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE HeiSeq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE CompEducInstSeq START WITH 1 INCREMENT BY 1;


CREATE OR REPLACE TRIGGER TrgEntrantBi
BEFORE INSERT ON Entrant
FOR EACH ROW
BEGIN
  IF :NEW.PK IS NULL THEN
    SELECT EntrantSeq.NEXTVAL INTO :NEW.PK FROM dual;
  END IF;
END;



CREATE OR REPLACE TRIGGER TrgSpecTestBi
BEFORE INSERT ON SpecTest
FOR EACH ROW
BEGIN
  IF :NEW.PK IS NULL THEN
    SELECT SpecTestSeq.NEXTVAL INTO :NEW.PK FROM dual;
  END IF;
END;


CREATE OR REPLACE TRIGGER TrgHeiSpecBi
BEFORE INSERT ON HeiSpec
FOR EACH ROW
BEGIN
  IF :NEW.PK IS NULL THEN
    SELECT HeiSpecSeq.NEXTVAL INTO :NEW.PK FROM dual;
  END IF;
END;


CREATE OR REPLACE TRIGGER TrgEntTestBi
BEFORE INSERT ON EntTest
FOR EACH ROW
BEGIN
  IF :NEW.PK IS NULL THEN
    SELECT EntTestSeq.NEXTVAL INTO :NEW.PK FROM dual;
  END IF;
END;


CREATE OR REPLACE TRIGGER TrgSpecBi
BEFORE INSERT ON Spec
FOR EACH ROW
BEGIN
  IF :NEW.PK IS NULL THEN
    SELECT SpecSeq.NEXTVAL INTO :NEW.PK FROM dual;
  END IF;
END;


CREATE OR REPLACE TRIGGER TrgHeiBi
BEFORE INSERT ON Hei
FOR EACH ROW
BEGIN
  IF :NEW.PK IS NULL THEN
    SELECT HeiSeq.NEXTVAL INTO :NEW.PK FROM dual;
  END IF;
END;


CREATE OR REPLACE TRIGGER TrgCompEducInstBi
BEFORE INSERT ON CompEducInst
FOR EACH ROW
BEGIN
  IF :NEW.PK IS NULL THEN
    SELECT CompEducInstSeq.NEXTVAL INTO :NEW.PK FROM dual;
  END IF;
END;


